<?php

/**
 * Debug Bar: panel "dumps" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;

?>
<h1>Dumped variables</h1>

<div class="tracy-inner tracy-DumpPanel">
<?php foreach ($this->data as $item): ?>
	<?php if ($item['title']):?>
	<h2><?php echo htmlspecialchars($item['title']) ?></h2>
	<?php endif ?>

	<table>
	<?php $i = 0 ?>
	<tr class="<?php echo $i++ % 2 ? 'tracy-alt' : '' ?>">
		<td><?php echo $item['dump'] ?></td>
	</tr>
	</table>
<?php endforeach ?>
</div>
